apiVersion: 'v2'
name: 'profilarr'
description: 'Configuration management platform for Radarr and Sonarr'
home: 'https://github.com/drinkataco/media-servarr/tree/main/charts/profilarr'
keywords:
  - 'radarr'
  - 'sonarr'
  - 'profiles'
  - 'formats'
  - 'profilarr'
kubeVersion: ">=1.24.0-0"
type: 'application'
version: 0.2.0
appVersion: v1.1.5
icon: 'https://github.com/drinkataco/media-servarr/blob/main/charts/profilarr/icon.png'
maintainers:
  - name: 'media-servarr'
    email: 'git@jo.shw.al'
    url: 'https://github.com/drinkataco/media-servarr/'
sources:
  - 'https://github.com/Dictionarry-Hub/profilarr'
  - 'https://dictionarry.dev/wiki/profilarr-setup'
  - 'https://github.com/drinkataco/media-servarr/tree/main/charts/profilarr'
dependencies:
  - name: 'media-servarr-base'
    version: 0.14.0
    repository: "file://../.."
