# Default library values
nameOverride: ''
fullnameOverride: ''

#
# Application Config
#
application:
  # main application web ui port
  port: 8191
  # access url base
  urlBase: 'flaresolverr'
  # Config is managed with environment variables in deployment.env
  # @see https://github.com/FlareSolverr/FlareSolverr#environment-variables

#
# Resource - DEPLOYMENT
# This is to set up and define the application deployment
#
deployment:
  container:
    image:
      repository: 'ghcr.io/flaresolverr/flaresolverr'

    # @see https://github.com/FlareSolverr/FlareSolverr?tab=readme-ov-file#environment-variables
    env:
      # - name: 'PROMETHEUS_ENABLED'
      #   value: '1'
      # - name: 'PROMETHEUS_PORT'
      #   value: '9702'

service:
  type: 'ClusterIP'
  ports:
    - targetPort: 'http' # The main port name is 'http', even though it isn't
      protocol: 'TCP'
      name: 'http'

ingress:
  enabled: true

# metrics:
# Metrics are enabled with environment variables in deployment.env
# @see https://github.com/FlareSolverr/FlareSolverr?tab=readme-ov-file#environment-variables
