# Default library values
nameOverride: ''
fullnameOverride: ''

#
# Application Config
#
application:
  # Main application web UI port
  port: 7575

#
# Resource - DEPLOYMENT
# This is to set up and define the application deployment
#
deployment:
  container:
    image:
      repository: 'ghcr.io/homarr-labs/homarr'

    # Additional volumeMounts on the output Deployment definition.
    volumeMounts:
      - name: 'app-data-configs'
        mountPath: '/app/data/configs'
      - name: 'data'
        mountPath: '/data'
      - name: 'app-data-icons'
        mountPath: '/app/data/icons'

  volumes:
    # Dashboard files
    app-data-configs:
    # Icons
    app-data-icons:
    # DB files
    data:
      persistentVolumeClaim:
        claimName: 'homarr-data'

persistentVolumeClaims:
  homarr-data:
    accessMode: 'ReadWriteOnce'
    requestStorage: '1Gi'
    selector: {}

ingress:
  enabled: true
  path: '/'
