apiVersion: 'v2'
name: 'tinymediamanager'
description: 'Media manager for movies and TV shows'
home: 'https://github.com/drinkataco/media-servarr/tree/main/charts/tinymediamanager'
keywords:
  - 'media'
  - 'metadata'
  - 'movies'
  - 'tv'
  - 'tinymediamanager'
kubeVersion: ">=1.24.0-0"
type: 'application'
version: 1.1.0
appVersion: 5.2.12
icon: 'https://github.com/drinkataco/media-servarr/blob/main/icon.png'
maintainers:
  - name: 'media-servarr'
    email: 'git@jo.shw.al'
    url: 'https://github.com/drinkataco/media-servarr/'
sources:
  - 'https://www.tinymediamanager.org/'
  - 'https://hub.docker.com/r/tinymediamanager/tinymediamanager'
  - 'https://github.com/drinkataco/media-servarr/tree/main/charts/tinymediamanager'
dependencies:
  - name: 'media-servarr-base'
    version: 0.14.0
    repository: "file://../.."
