# Default library values
nameOverride: ''
fullnameOverride: ''

#
# Application Config
#
application:
  # BASEURL is not supported out of the box, and will have to be configured with ingress
  # @see https://github.com/sct/overseerr/issues/274
  # Main application web UI port
  port: 5055
  # Example - ConfigMap for core application settings
  config:
    filename: 'settings.json'
    contents: |
      {
        "main": {
          "applicationUrl": "http://jellyseerr.media-servarr.local/"
        }
      }
    mountPath: '/app/config/settings.json'

#
# Resource - DEPLOYMENT
# This is to set up and define the application deployment
#
deployment:
  container:
    image:
      repository: 'fallenbagel/jellyseerr'

    # Additional volumeMounts on the output Deployment definition.
    volumeMounts:
      - name: 'config'
        mountPath: '/app/config'

  volumes:
    config:
      persistentVolumeClaim:
        claimName: 'jellyseerr-config'

persistentVolumeClaims:
  jellyseerr-config:
    accessMode: 'ReadWriteOnce'
    requestStorage: '1Gi'
    selector: {}

ingress:
  enabled: true
  host: 'jellyseerr.media-servarr.local'
