{{- define "media-servarr-base.service" -}}
---

apiVersion: 'v1'
kind: 'Service'
metadata:
  name: {{ include "media-servarr-base.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "media-servarr-base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
    {{- if .Values.metrics.enabled }}
    - name: '{{ .Values.metrics.port.name }}'
      port: {{ .Values.metrics.port.number }}
    {{- end }}
  selector:
    {{- include "media-servarr-base.selectorLabels" . | nindent 4 }}
{{- end }}
